<script setup lang="ts">
import { computed, ref } from 'vue'

type Dish = { name: string; price: string; description: string; category: string; image: string }
const selectedCategory = ref('Todos')
const feedbackSent = ref(false)
const reservationSent = ref(false)
const feedback = ref({ name: '', note: '', comment: '' })
const dishes: Dish[] = [
	{ name: 'Salada da estação', price: 'R$ 28', description: 'Folhas, legumes grelhados, castanhas e vinagrete de ervas.', category: 'Entradas', image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=85' },
	{ name: 'Pão de milho', price: 'R$ 22', description: 'Assado na brasa, manteiga de garrafa e melado da casa.', category: 'Entradas', image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85' },
	{ name: 'Carne na brasa', price: 'R$ 62', description: 'Corte do dia, purê de mandioca e vinagrete de pimenta.', category: 'Pratos principais', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=85' },
	{ name: 'Peixe do litoral', price: 'R$ 58', description: 'Pesca sustentável, arroz cremoso e molho de tucupi.', category: 'Pratos principais', image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=900&q=85' },
	{ name: 'Doce de leite queimado', price: 'R$ 24', description: 'Crocante de castanha e sorvete de queijo meia cura.', category: 'Sobremesas', image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=900&q=85' },
	{ name: 'Chocolate e café', price: 'R$ 26', description: 'Creme intenso, farofa de café e flor de sal.', category: 'Sobremesas', image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=85' },
]
const filteredDishes = computed(() => selectedCategory.value === 'Todos' ? dishes : dishes.filter((dish) => dish.category === selectedCategory.value))
function submitFeedback(event: Event) {
	const data = new FormData(event.target as HTMLFormElement)
	feedback.value = { name: String(data.get('name') || 'Cliente da casa'), note: String(data.get('note') || ''), comment: String(data.get('comment') || '') }
	feedbackSent.value = true
}
function submitReservation() { reservationSent.value = true }
</script>

<template>
	<main>
		<section id="inicio" class="hero section-dark"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow light">Cozinha brasileira contemporânea</p><h1>Comida<br />que conta<br />histórias.</h1><p class="lead light-text">Ingredientes da nossa terra, fogo baixo e encontros à mesa.<br />Uma experiência acolhedora no coração da cidade.</p><a class="button gold" href="#cardapio">Conheça o cardápio <span>→</span></a></div><div class="hero-image image-frame"><img src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=85" alt="Salão acolhedor do restaurante" /></div></div></section>
		<section id="sobre" class="section-cream"><div class="container two-columns"><img class="story-image" src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1000&q=85" alt="Interior acolhedor do restaurante" /><div><p class="eyebrow">Nossa história</p><h2>Da brasa para a<br />sua mesa.</h2><p class="body-copy">O Mesa &amp; Brasa nasceu do desejo de celebrar sabores brasileiros com técnica, afeto e respeito aos pequenos produtores. Nosso menu muda com a estação para que cada visita traga uma descoberta.</p><div class="principles"><article><strong>01 / Origem</strong><span>Ingredientes locais</span></article><article><strong>02 / Fogo</strong><span>Preparo cuidadoso</span></article><article><strong>03 / Encontro</strong><span>Receber bem</span></article></div></div></div></section>
		<section id="galeria" class="section-cream"><div class="container"><p class="eyebrow">Galeria e destaques</p><h2>Um lugar para ficar.</h2><div class="gallery-grid"><img class="gallery-large" src="https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1100&q=85" alt="Salão do restaurante" /><img src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=700&q=85" alt="Mesa preparada" /><img src="https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=700&q=85" alt="Terraço do restaurante" /><img src="https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=700&q=85" alt="Prato da casa" /></div></div></section>
		<section id="cardapio" class="section-white"><div class="container"><p class="eyebrow">Produtos e serviços</p><h2>O cardápio da casa.</h2><p class="body-copy intro">Escolha uma categoria para conhecer os pratos preparados diariamente pela nossa cozinha.</p><div class="filters"><button v-for="category in ['Todos', 'Entradas', 'Pratos principais', 'Sobremesas']" :key="category" :class="{ active: selectedCategory === category }" @click="selectedCategory = category">{{ category }}</button></div><div class="dish-grid"><article v-for="dish in filteredDishes" :key="dish.name" class="dish"><img :src="dish.image" :alt="dish.name" /><div class="dish-info"><div><h3>{{ dish.name }}</h3><strong>{{ dish.price }}</strong></div><p>{{ dish.description }}</p></div></article></div></div></section>
		<section id="feedback" class="section-sand"><div class="container feedback-layout"><div class="feedback-intro"><p class="eyebrow">A voz dos clientes</p><h2>Conte como foi<br />sua experiência.</h2><p class="body-copy">Sua opinião ajuda nossa equipe a cuidar ainda melhor de cada detalhe, do primeiro prato ao último café.</p><blockquote>“A comida tem sabor de casa, mas com uma apresentação impecável.”<cite>Marina, cliente da casa</cite></blockquote></div><div class="feedback-panel"><form @submit.prevent="submitFeedback"><div class="form-row"><label>Nome<input name="name" required placeholder="Seu nome" /></label><label>Nota<select name="note" required><option value="">Escolha uma nota</option><option>5 - Excelente</option><option>4 - Muito bom</option><option>3 - Bom</option></select></label></div><label>Seu comentário<textarea name="comment" required placeholder="O que você achou da experiência?"></textarea></label><button class="button gold" type="submit">Enviar feedback →</button></form><div v-if="feedbackSent" class="feedback-result"><p class="feedback-success" role="status">Obrigado por compartilhar sua experiência. Seu feedback foi enviado!</p><article class="submitted-feedback"><p class="eyebrow">Seu feedback</p><div class="submitted-rating">{{ feedback.note }}</div><p>“{{ feedback.comment }}”</p><strong>{{ feedback.name }}</strong></article></div></div></div></section>
		<section id="reservas" class="section-green"><div class="container two-columns feedback-grid"><div><p class="eyebrow light">Contato e reservas</p><h2>Seu lugar está à<br />mesa.</h2><p class="lead light-text">Atendemos de terça a domingo, das 12h às 23h. Preencha o formulário e nossa equipe confirmará sua reserva.</p></div><form @submit.prevent="submitReservation"><div class="form-row"><label>Nome<input required placeholder="Seu nome" /></label><label>E-mail<input required type="email" placeholder="voce@email.com" /></label></div><div class="form-row"><label>Data<input required type="date" /></label><label>Pessoas<input required type="number" min="1" value="2" /></label></div><label>Observações<textarea placeholder="Alguma preferência? (opcional)"></textarea></label><button class="button gold" type="submit">{{ reservationSent ? 'Solicitação enviada ✓' : 'Solicitar reserva →' }}</button></form></div></section>
	</main>
</template>
